### ISSUE TITLE
add link to change log

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-ost/ss3-website#11]
I just noticed that the link to the change log in the 3.30.22 Release Notes.pdf is broken.
I suggest that we add to the website a link to the changelog so that users will have an alternative way to find it.

**Comment by e-perl-NOAA** [comment]
Yes, that's because it was prior to moving to github enterprise and so the link has changed.

**Comment by e-perl-NOAA** [comment]
There is a link to the change log on the website under the [Installing Stock Synthesis portion of the landing page](https://nmfs-ost.github.io/ss3-website/#installing-stock-synthesis). Is there a better place that you think it should go? I could move the Installing Stock Synthesis portion to the top under news.

**Comment by Rick-Methot-NOAA** [comment]
I was thinking of the righthand sidebar.  Or perhaps close to links to documentation.

**Comment by e-perl-NOAA** [comment]
Does the addition of the change log to the sidebar look good to you (see change [here](https://nmfs-ost.github.io/ss3-website/))?

**Comment by Rick-Methot-NOAA** [comment]
Just right.  Thanks
