### ISSUE TITLE
change links in "Tools for working with Stock Synthesis" to github.io sites?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-website#14]
I think all the packages listed under "Tools for working with Stock Synthesis" have github.io sites that are probably the better landing pages for those unfamiliar with these tools than the main github code repositories.

@e-perl-NOAA what do you think?

**Comment by e-perl-NOAA** [comment]
Most do but the simple stock synthesis, xsss, and the SAC tool don't. Happy to add the github site rather than the repo pages.

**Comment by e-perl-NOAA** [comment]
Resolved in most recent commit https://github.com/nmfs-ost/ss3-website/commit/d7278a36b76ba2739e6110001416b307cb75ab2d.
