### ISSUE TITLE
add older change logs to augment the SS3 history

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-ost/ss3-website#15]
Excel and text based change logs exist from 2003 through July 2020 when the github repo was created.
Propose to create a zip with all this material for posterity.

 This collection contains:
ReadMe for Stock Synthesis historical change logs
"SS2-notes.txt" initial development of first ADMB version of SS during Sept 2003 to early 2004 leading to SS2 V1.00.
No change log found for subsequent development of multiple versions culminating in V2007-1.00b in July 2006.

development of version 3 during 2007-2009 is in about 25 folders in C:\Users\Richard.Methot\Documents\SS_Model\Versions\Ver300\V30developmental.
each folder has the tpl and the exe.  Some have readme.txt files
Some described in "Readme-V2.00.doc"  Mar 2007 through Jan 2008

"Change log for SS 3.24.xlsx" covers version 3.02e (Feb 2009) through 3.24AC (April 2017) 

"Change log for SS3.30.xlsx" covers 3.30.00 (Nov 2016) through 3.30.15.09 (July 2020)

Subsequent changes are found in github at:  https://github.com/nmfs-ost/ss3-source-code

**Comment by Rick-Methot-NOAA** [comment]
[Stock_Synthesis_ChangeLogs.zip](https://github.com/user-attachments/files/17910173/Stock_Synthesis_ChangeLogs.zip)

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA I already have a link to a change log that has 3.30.00 - 3.30.19 on the website in the change log section (see [here](https://github.com/nmfs-ost/ss3-source-code/blob/v3.30.19/Change_log_for_SS_3.30.xlsx?raw=true)). Is it okay to leave that one up and just add the other excel file for 3.24 and the txt file that you included in the zip?

**Comment by Rick-Methot-NOAA** [comment]
Of course.  I may add more later to augment the collection but you have a good start.

**Comment by e-perl-NOAA** [comment]
Completed with commit 39b1a5c911e77ec9c879f70d13cb0c56f0866ce7
