### ISSUE TITLE
add core documents to website

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-ost/ss3-website#22]
add:
Methot and Wetzel (2013) to the website.  with separate entry for the technical appendix

https://www.sciencedirect.com/science/article/pii/S0165783612003293#sec0120

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa started to convert the technical document appendix into Rmarkdown as discussed in https://github.com/nmfs-ost/ss3-doc/issues/2. The files are stored in a "technical_description" folder within the ss3-doc repo with the compiled PDF at https://github.com/nmfs-ost/ss3-doc/blob/main/technical_description/_main.pdf.

Unofortunately it would take some work to finish this process, but I'm guessing that it would be better to complete that than post the 2013 appendix which is a bit out of date and also available via the journal article.

**Comment by Rick-Methot-NOAA** [comment]
Understood and I also worry about how dated and incomplete the tech doc is.  
Let's not post the docs but do provide a sentence ort two on the website explaining that equations behind the basic features of SS3 are found in Appendix A of Methot and Wetzel (2013).

**Comment by iantaylor-NOAA** [comment]
That sounds good to me.

**Comment by Rick-Methot-NOAA** [comment]
works for me
