### ISSUE TITLE
ss3-website initial framework

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-ost/ss3-website#3]
In developing a new website for SS3, we need to create a framework for what types of pages/information/vignettes we would like to include in the website. Not all of these pages need to be put together for us to officially publish the new website, but a tab with an "under construction" image on that page will at least let users know what a particular page will contain.

The current pages are:
- [Main landing page (Index)](https://nmfs-ost.github.io/ss3-website/)
- SS3 User Manuals
         - [Citing the SS3 User Manual](https://nmfs-ost.github.io/ss3-website/qmds/user_manual.html)
         - [HTML Version](https://nmfs-ost.github.io/ss3-doc/SS330_User_Manual_release.html)
         - PDF Version (downloads pdf)
- Tutorials for Getting Started
         - [Getting Started with Stock Synthesis](https://nmfs-ost.github.io/ss3-website/qmds/getting_started_ss3.html)
         - [Developing Your First Stock Synthesis Model](https://nmfs-ost.github.io/ss3-website/qmds/ss3_model_tips.html)
         - [Important SS3 Set-Up Decisions](https://nmfs-ost.github.io/ss3-website/qmds/ss3_setup_decisions.html)
- Vignettes for Model Features
         - [Start Year Considerations](https://nmfs-ost.github.io/ss3-website/qmds/start_year_considerations.html) (still needs pictures according to the [word document](https://docs.google.com/document/d/160yKgDVe77KD9ca7_7HJgAc-hkLL8HMS1RIrwvxyC2I/edit?usp=drive_link) this was taken from, @Rick-Methot-NOAA what pictures were you imagining there?)
         - [Predators](https://nmfs-ost.github.io/ss3-website/qmds/predator.html)
         - [Settlement Timing](https://nmfs-ost.github.io/ss3-website/qmds/settlement_timing.html)

What other pages/info should be included? Any suggestions would be helpful! Feel free to make edits/suggestions in a branch and submit a PR.

Goal for switching to the new website: January/February 2024

**Comment by iantaylor-NOAA** [comment]
The website is a big improvement. I can't think of specific info that should be added at this point and it seems that we can extend and expand at any time after rolling out the initial site in a month or two.

I'm particularly impressed by the flowcharts in the Important SS3 Set-up Decisions page and the fact that the flowcharts are based on an easy to read script where changes can be tracked by git: https://github.com/nmfs-ost/ss3-website/blob/main/website/qmds/ss3_setup_decisions.qmd so I can make suggestions via Pull Request.

**Comment by Rick-Methot-NOAA** [comment]
Yes!  This is looking great.  Agree with Ian about the flowcharts, which have great potential.  Flagging them for Jason: @shcaba
